# Generated by Django 4.2.7 on 2025-09-30 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cnic",
            field=models.CharField(
                help_text="13-digit CNIC (e.g., 12345-1234567-1)",
                max_length=15,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="pin",
            field=models.CharField(default="1234", max_length=4),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid Pakistani phone number (03XXXXXXXXX or +923XXXXXXXXX)",
                        regex="^(03|\\+923)\\d{9}$",
                    )
                ],
            ),
        ),
    ]
