# Generated by Django 4.2.7 on 2025-09-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_balance_alter_profile_cnic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="profile",
            name="pin",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
