# Generated by Django 4.2.7 on 2025-09-30 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_balance_alter_profile_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid 11-digit phone number starting with 0",
                        regex="^0\\d{10}$",
                    )
                ],
            ),
        ),
    ]
