# Generated by Django 4.2.7 on 2025-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
